"""Add the embeddable widget tables.

Revision ID: 0006_embed_widgets
Revises: 0005_audit_services
Create Date: 2026-09-05

app/models/embed_widgets.py declared four tables but was never imported by
app.models, so - exactly like capi_delivery in 0004 - its metadata
never reached the baseline's create_all and the tables were never created
in any database.

This one is not dormant either. app/api/v1/endpoints/embed_widgets.py,
app/services/embed_widgets/token_service.py and widget_service.py
import these models at module scope, so every embed widget request was
querying tables that do not exist.

The module is now registered, which puts it in target_metadata; this is
the ordinary Alembic diff creating what registration added. Purely additive,
and the module declares no SQLAlchemy Enum, so there are no PostgreSQL enum
types to manage.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '0006_embed_widgets'
down_revision = '0005_audit_services'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embed_widget_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('view_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_domain', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embed_widget_views'))
    )
    op.create_index('ix_embed_widget_views_tenant_date', 'embed_widget_views', ['tenant_id', 'view_date'], unique=False)
    op.create_index(op.f('ix_embed_widget_views_tenant_id'), 'embed_widget_views', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_embed_widget_views_token_id'), 'embed_widget_views', ['token_id'], unique=False)
    op.create_index('ix_embed_widget_views_widget_date', 'embed_widget_views', ['widget_id', 'view_date'], unique=False)
    op.create_index(op.f('ix_embed_widget_views_widget_id'), 'embed_widget_views', ['widget_id'], unique=False)
    op.create_table('embed_domain_whitelist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain_pattern', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_embed_domain_whitelist_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embed_domain_whitelist')),
    sa.UniqueConstraint('tenant_id', 'domain_pattern', name='uq_embed_domain_whitelist_tenant_domain')
    )
    op.create_index('ix_embed_domain_whitelist_tenant', 'embed_domain_whitelist', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_embed_domain_whitelist_tenant_id'), 'embed_domain_whitelist', ['tenant_id'], unique=False)
    op.create_table('embed_widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('widget_size', sa.String(length=50), nullable=False),
    sa.Column('custom_width', sa.Integer(), nullable=True),
    sa.Column('custom_height', sa.Integer(), nullable=True),
    sa.Column('branding_level', sa.String(length=50), nullable=False),
    sa.Column('custom_logo_url', sa.String(length=512), nullable=True),
    sa.Column('custom_accent_color', sa.String(length=7), nullable=True),
    sa.Column('custom_background_color', sa.String(length=7), nullable=True),
    sa.Column('custom_text_color', sa.String(length=7), nullable=True),
    sa.Column('data_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_views', sa.BigInteger(), nullable=False),
    sa.Column('total_unique_domains', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_embed_widgets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embed_widgets'))
    )
    op.create_index('ix_embed_widgets_active', 'embed_widgets', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_embed_widgets_tenant', 'embed_widgets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_embed_widgets_tenant_id'), 'embed_widgets', ['tenant_id'], unique=False)
    op.create_index('ix_embed_widgets_type', 'embed_widgets', ['tenant_id', 'widget_type'], unique=False)
    op.create_table('embed_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('allowed_domains', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('current_minute_requests', sa.Integer(), nullable=False),
    sa.Column('current_minute_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.BigInteger(), nullable=False),
    sa.Column('total_errors', sa.BigInteger(), nullable=False),
    sa.Column('last_origin', sa.String(length=512), nullable=True),
    sa.Column('suspicious_activity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_embed_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['embed_widgets.id'], name=op.f('fk_embed_tokens_widget_id_embed_widgets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embed_tokens'))
    )
    op.create_index('ix_embed_tokens_hash', 'embed_tokens', ['token_hash'], unique=False)
    op.create_index('ix_embed_tokens_prefix', 'embed_tokens', ['token_prefix'], unique=False)
    op.create_index('ix_embed_tokens_status', 'embed_tokens', ['status'], unique=False)
    op.create_index('ix_embed_tokens_tenant', 'embed_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_embed_tokens_tenant_id'), 'embed_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_embed_tokens_widget', 'embed_tokens', ['widget_id'], unique=False)
    op.create_index(op.f('ix_embed_tokens_widget_id'), 'embed_tokens', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embed_tokens_widget_id'), table_name='embed_tokens')
    op.drop_index('ix_embed_tokens_widget', table_name='embed_tokens')
    op.drop_index(op.f('ix_embed_tokens_tenant_id'), table_name='embed_tokens')
    op.drop_index('ix_embed_tokens_tenant', table_name='embed_tokens')
    op.drop_index('ix_embed_tokens_status', table_name='embed_tokens')
    op.drop_index('ix_embed_tokens_prefix', table_name='embed_tokens')
    op.drop_index('ix_embed_tokens_hash', table_name='embed_tokens')
    op.drop_table('embed_tokens')
    op.drop_index('ix_embed_widgets_type', table_name='embed_widgets')
    op.drop_index(op.f('ix_embed_widgets_tenant_id'), table_name='embed_widgets')
    op.drop_index('ix_embed_widgets_tenant', table_name='embed_widgets')
    op.drop_index('ix_embed_widgets_active', table_name='embed_widgets')
    op.drop_table('embed_widgets')
    op.drop_index(op.f('ix_embed_domain_whitelist_tenant_id'), table_name='embed_domain_whitelist')
    op.drop_index('ix_embed_domain_whitelist_tenant', table_name='embed_domain_whitelist')
    op.drop_table('embed_domain_whitelist')
    op.drop_index(op.f('ix_embed_widget_views_widget_id'), table_name='embed_widget_views')
    op.drop_index('ix_embed_widget_views_widget_date', table_name='embed_widget_views')
    op.drop_index(op.f('ix_embed_widget_views_token_id'), table_name='embed_widget_views')
    op.drop_index(op.f('ix_embed_widget_views_tenant_id'), table_name='embed_widget_views')
    op.drop_index('ix_embed_widget_views_tenant_date', table_name='embed_widget_views')
    op.drop_table('embed_widget_views')
    # ### end Alembic commands ###
