"""Add the audit-recommended service tables.

Revision ID: 0005_audit_services
Revises: 0004_capi_delivery_tables
Create Date: 2026-09-05

app/models/audit_services.py was never reachable: it raised on import
(metadata is reserved by the Declarative API, and its CompetitorBenchmark
collided with the base model's competitor_benchmarks table), so it was
never listed in app/models/__init__.py and never reached
Base.metadata. The 0001 baseline builds the schema with
Base.metadata.create_all after import app.models, so none of these 18
tables have ever been created in any database.

The module is now importable and registered, which puts it in
target_metadata; this revision is the ordinary Alembic diff that creates
what registration added. Purely additive - it touches no pre-existing table.

downgrade drops the five enum types along with the tables. Alembic's
autogenerate does not emit those drops, and without them a downgrade leaves
the types behind and the next upgrade fails with
type "customersegment" already exists.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0005_audit_services"
down_revision = "0004_capi_delivery_tables"
branch_labels = None
depends_on = None


ENUM_TYPES = {
    "conversionuploadstatus": ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED',),
    "customersegment": ('VIP', 'HIGH_VALUE', 'MEDIUM_VALUE', 'LOW_VALUE', 'AT_RISK',),
    "emqstatus": ('PENDING', 'CALCULATED', 'FAILED',),
    "experimentstatus": ('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED',),
    "reallocationstatus": ('PROPOSED', 'APPROVED', 'EXECUTING', 'COMPLETED', 'ROLLED_BACK', 'REJECTED',),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The 0001 baseline calls create_all() on the shared MetaData, and SQLAlchemy
    # creates every enum type bound to that MetaData even for tables it is not
    # creating. So on a fresh database these five types already exist, while on
    # a database stamped before this revision they do not. Create them with
    # checkfirst and keep create_type=False on the columns below, so both paths
    # work.
    bind = op.get_bind()
    for _enum_name, _values in ENUM_TYPES.items():
        postgresql.ENUM(*_values, name=_enum_name).create(bind, checkfirst=True)
    op.create_table('audience_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('audience_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('lookalike_percent', sa.Float(), nullable=True),
    sa.Column('source_audience_id', sa.String(length=255), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('expansion_potential', sa.String(length=20), nullable=True),
    sa.Column('current_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('historical_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_ltv', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audience_records_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_records')),
    sa.UniqueConstraint('tenant_id', 'platform', 'external_id', name='uq_audience')
    )
    op.create_index('ix_audience_external', 'audience_records', ['tenant_id', 'platform', 'external_id'], unique=False)
    op.create_index('ix_audience_tenant', 'audience_records', ['tenant_id'], unique=False)
    op.create_table('conversion_latencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversion_latencies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_latencies'))
    )
    op.create_index('ix_conv_latency_platform', 'conversion_latencies', ['tenant_id', 'platform', 'event_type'], unique=False)
    op.create_index('ix_conv_latency_tenant', 'conversion_latencies', ['tenant_id', 'event_time'], unique=False)
    op.create_table('conversion_latency_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('median_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Integer(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversion_latency_stats_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_latency_stats')),
    sa.UniqueConstraint('tenant_id', 'period_date', 'platform', 'event_type', name='uq_latency_stats')
    )
    op.create_index('ix_latency_stats_tenant', 'conversion_latency_stats', ['tenant_id', 'period_date'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('creative_type', sa.String(length=50), nullable=True),
    sa.Column('asset_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('creative_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_creatives_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creatives')),
    sa.UniqueConstraint('tenant_id', 'platform', 'external_id', name='uq_creative')
    )
    op.create_index('ix_creative_external', 'creatives', ['tenant_id', 'platform', 'external_id'], unique=False)
    op.create_index('ix_creative_tenant', 'creatives', ['tenant_id'], unique=False)
    op.create_table('customer_ltv_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_channel', sa.String(length=100), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('avg_order_value_cents', sa.Integer(), nullable=True),
    sa.Column('days_since_last_order', sa.Integer(), nullable=True),
    sa.Column('predicted_ltv_30d_cents', sa.BigInteger(), nullable=True),
    sa.Column('predicted_ltv_90d_cents', sa.BigInteger(), nullable=True),
    sa.Column('predicted_ltv_365d_cents', sa.BigInteger(), nullable=True),
    sa.Column('predicted_ltv_lifetime_cents', sa.BigInteger(), nullable=True),
    sa.Column('segment', postgresql.ENUM('VIP', 'HIGH_VALUE', 'MEDIUM_VALUE', 'LOW_VALUE', 'AT_RISK', name='customersegment', create_type=False), nullable=True),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('max_cac_cents', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_customer_ltv_predictions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_ltv_predictions'))
    )
    op.create_index('ix_ltv_pred_customer', 'customer_ltv_predictions', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_ltv_pred_segment', 'customer_ltv_predictions', ['tenant_id', 'segment'], unique=False)
    op.create_index('ix_ltv_pred_tenant', 'customer_ltv_predictions', ['tenant_id', 'predicted_at'], unique=False)
    op.create_table('emq_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('pixel_id', sa.String(length=255), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('parameter_quality', sa.Float(), nullable=True),
    sa.Column('deduplication_quality', sa.Float(), nullable=True),
    sa.Column('event_coverage', sa.Float(), nullable=True),
    sa.Column('events_received', sa.Integer(), nullable=False),
    sa.Column('events_matched', sa.Integer(), nullable=False),
    sa.Column('events_attributed', sa.Integer(), nullable=False),
    sa.Column('email_match_rate', sa.Float(), nullable=True),
    sa.Column('phone_match_rate', sa.Float(), nullable=True),
    sa.Column('combined_match_rate', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CALCULATED', 'FAILED', name='emqstatus', create_type=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_emq_measurements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emq_measurements')),
    sa.UniqueConstraint('tenant_id', 'platform', 'pixel_id', 'measurement_date', 'event_type', name='uq_emq_measurement')
    )
    op.create_index('ix_emq_platform', 'emq_measurements', ['tenant_id', 'platform', 'pixel_id'], unique=False)
    op.create_index('ix_emq_tenant_date', 'emq_measurements', ['tenant_id', 'measurement_date'], unique=False)
    op.create_table('industry_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('your_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('industry_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('percentile_rankings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('metrics_above_median', sa.Integer(), nullable=False),
    sa.Column('metrics_below_median', sa.Integer(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_industry_benchmarks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_benchmarks'))
    )
    op.create_index('ix_benchmark_industry', 'industry_benchmarks', ['tenant_id', 'industry', 'platform'], unique=False)
    op.create_index('ix_benchmark_tenant', 'industry_benchmarks', ['tenant_id', 'date'], unique=False)
    op.create_table('ltv_cohort_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cohort_month', sa.String(length=7), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('avg_ltv_cents', sa.BigInteger(), nullable=True),
    sa.Column('median_ltv_cents', sa.BigInteger(), nullable=True),
    sa.Column('ltv_p90_cents', sa.BigInteger(), nullable=True),
    sa.Column('avg_orders', sa.Float(), nullable=True),
    sa.Column('avg_retention_days', sa.Float(), nullable=True),
    sa.Column('segment_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ltv_cohort_analyses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ltv_cohort_analyses')),
    sa.UniqueConstraint('tenant_id', 'cohort_month', name='uq_ltv_cohort')
    )
    op.create_index('ix_ltv_cohort_tenant', 'ltv_cohort_analyses', ['tenant_id'], unique=False)
    op.create_table('model_retraining_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('training_start_date', sa.Date(), nullable=True),
    sa.Column('training_end_date', sa.Date(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('old_version', sa.String(length=50), nullable=True),
    sa.Column('new_version', sa.String(length=50), nullable=True),
    sa.Column('old_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_model_retraining_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_retraining_jobs'))
    )
    op.create_index('ix_retrain_job_model', 'model_retraining_jobs', ['model_name', 'created_at'], unique=False)
    op.create_index('ix_retrain_job_status', 'model_retraining_jobs', ['status'], unique=False)
    op.create_index('ix_retrain_job_tenant', 'model_retraining_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('audience_overlaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('audience_id_1', sa.UUID(), nullable=False),
    sa.Column('audience_id_2', sa.UUID(), nullable=False),
    sa.Column('overlap_percent', sa.Float(), nullable=False),
    sa.Column('overlap_size', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audience_id_1'], ['audience_records.id'], name=op.f('fk_audience_overlaps_audience_id_1_audience_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audience_id_2'], ['audience_records.id'], name=op.f('fk_audience_overlaps_audience_id_2_audience_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audience_overlaps_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_overlaps'))
    )
    op.create_index('ix_overlap_audiences', 'audience_overlaps', ['audience_id_1', 'audience_id_2'], unique=False)
    op.create_index('ix_overlap_tenant', 'audience_overlaps', ['tenant_id'], unique=False)
    op.create_table('creative_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('spend_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('cpc_cents', sa.Integer(), nullable=True),
    sa.Column('cpm_cents', sa.Integer(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=False),
    sa.Column('video_completions', sa.Integer(), nullable=False),
    sa.Column('engagements', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], name=op.f('fk_creative_performance_creative_id_creatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_creative_performance_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_performance')),
    sa.UniqueConstraint('creative_id', 'date', 'campaign_id', name='uq_creative_perf')
    )
    op.create_index('ix_creative_perf_creative', 'creative_performance', ['creative_id', 'date'], unique=False)
    op.create_index('ix_creative_perf_tenant', 'creative_performance', ['tenant_id', 'date'], unique=False)
    op.create_table('budget_reallocation_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_current_budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_new_budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('campaigns_affected', sa.Integer(), nullable=False),
    sa.Column('projected_roas_change', sa.Float(), nullable=True),
    sa.Column('projected_spend_change', sa.Float(), nullable=True),
    sa.Column('projected_revenue_change', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('PROPOSED', 'APPROVED', 'EXECUTING', 'COMPLETED', 'ROLLED_BACK', 'REJECTED', name='reallocationstatus', create_type=False), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_budget_reallocation_plans_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_budget_reallocation_plans_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_budget_reallocation_plans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_reallocation_plans'))
    )
    op.create_index('ix_realloc_plan_status', 'budget_reallocation_plans', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_realloc_plan_tenant', 'budget_reallocation_plans', ['tenant_id', 'created_at'], unique=False)
    op.create_table('creative_fatigue_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('current_ctr', sa.Float(), nullable=True),
    sa.Column('baseline_ctr', sa.Float(), nullable=True),
    sa.Column('ctr_decline_percent', sa.Float(), nullable=True),
    sa.Column('current_frequency', sa.Float(), nullable=True),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_creative_fatigue_alerts_acknowledged_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], name=op.f('fk_creative_fatigue_alerts_creative_id_creatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_creative_fatigue_alerts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_fatigue_alerts'))
    )
    op.create_index('ix_fatigue_alert_creative', 'creative_fatigue_alerts', ['creative_id'], unique=False)
    op.create_index('ix_fatigue_alert_tenant', 'creative_fatigue_alerts', ['tenant_id', 'created_at'], unique=False)
    op.create_table('model_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('champion_version', sa.String(length=50), nullable=False),
    sa.Column('challenger_version', sa.String(length=50), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='experimentstatus', create_type=False), nullable=False),
    sa.Column('min_samples', sa.Integer(), nullable=False),
    sa.Column('significance_threshold', sa.Float(), nullable=False),
    sa.Column('primary_metric', sa.String(length=50), nullable=False),
    sa.Column('champion_predictions', sa.Integer(), nullable=False),
    sa.Column('challenger_predictions', sa.Integer(), nullable=False),
    sa.Column('champion_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenger_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winner', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('confidence_interval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_model_experiments_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_model_experiments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_experiments'))
    )
    op.create_index('ix_model_exp_model', 'model_experiments', ['tenant_id', 'model_name'], unique=False)
    op.create_index('ix_model_exp_status', 'model_experiments', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_model_exp_tenant', 'model_experiments', ['tenant_id'], unique=False)
    op.create_table('offline_conversion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('upload_type', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('successful_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='conversionuploadstatus', create_type=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_batch_id', sa.String(length=255), nullable=True),
    sa.Column('platform_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_offline_conversion_batches_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offline_conversion_batches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_conversion_batches'))
    )
    op.create_index('ix_offline_batch_status', 'offline_conversion_batches', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_offline_batch_tenant', 'offline_conversion_batches', ['tenant_id', 'created_at'], unique=False)
    op.create_table('budget_reallocation_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_name', sa.String(length=500), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('current_budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('new_budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['budget_reallocation_plans.id'], name=op.f('fk_budget_reallocation_changes_plan_id_budget_reallocation_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_reallocation_changes'))
    )
    op.create_index('ix_realloc_change_plan', 'budget_reallocation_changes', ['plan_id'], unique=False)
    op.create_table('experiment_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['model_experiments.id'], name=op.f('fk_experiment_predictions_experiment_id_model_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_predictions'))
    )
    op.create_index('ix_exp_pred_experiment', 'experiment_predictions', ['experiment_id'], unique=False)
    op.create_index('ix_exp_pred_variant', 'experiment_predictions', ['experiment_id', 'variant'], unique=False)
    op.create_table('offline_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('click_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_event_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.Column('upload_attempts', sa.Integer(), nullable=False),
    sa.Column('last_upload_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['offline_conversion_batches.id'], name=op.f('fk_offline_conversions_batch_id_offline_conversion_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offline_conversions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_conversions'))
    )
    op.create_index('ix_offline_conv_batch', 'offline_conversions', ['batch_id'], unique=False)
    op.create_index('ix_offline_conv_tenant', 'offline_conversions', ['tenant_id', 'event_time'], unique=False)
    op.create_index('ix_offline_conv_uploaded', 'offline_conversions', ['tenant_id', 'uploaded'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offline_conv_uploaded', table_name='offline_conversions')
    op.drop_index('ix_offline_conv_tenant', table_name='offline_conversions')
    op.drop_index('ix_offline_conv_batch', table_name='offline_conversions')
    op.drop_table('offline_conversions')
    op.drop_index('ix_exp_pred_variant', table_name='experiment_predictions')
    op.drop_index('ix_exp_pred_experiment', table_name='experiment_predictions')
    op.drop_table('experiment_predictions')
    op.drop_index('ix_realloc_change_plan', table_name='budget_reallocation_changes')
    op.drop_table('budget_reallocation_changes')
    op.drop_index('ix_offline_batch_tenant', table_name='offline_conversion_batches')
    op.drop_index('ix_offline_batch_status', table_name='offline_conversion_batches')
    op.drop_table('offline_conversion_batches')
    op.drop_index('ix_model_exp_tenant', table_name='model_experiments')
    op.drop_index('ix_model_exp_status', table_name='model_experiments')
    op.drop_index('ix_model_exp_model', table_name='model_experiments')
    op.drop_table('model_experiments')
    op.drop_index('ix_fatigue_alert_tenant', table_name='creative_fatigue_alerts')
    op.drop_index('ix_fatigue_alert_creative', table_name='creative_fatigue_alerts')
    op.drop_table('creative_fatigue_alerts')
    op.drop_index('ix_realloc_plan_tenant', table_name='budget_reallocation_plans')
    op.drop_index('ix_realloc_plan_status', table_name='budget_reallocation_plans')
    op.drop_table('budget_reallocation_plans')
    op.drop_index('ix_creative_perf_tenant', table_name='creative_performance')
    op.drop_index('ix_creative_perf_creative', table_name='creative_performance')
    op.drop_table('creative_performance')
    op.drop_index('ix_overlap_tenant', table_name='audience_overlaps')
    op.drop_index('ix_overlap_audiences', table_name='audience_overlaps')
    op.drop_table('audience_overlaps')
    op.drop_index('ix_retrain_job_tenant', table_name='model_retraining_jobs')
    op.drop_index('ix_retrain_job_status', table_name='model_retraining_jobs')
    op.drop_index('ix_retrain_job_model', table_name='model_retraining_jobs')
    op.drop_table('model_retraining_jobs')
    op.drop_index('ix_ltv_cohort_tenant', table_name='ltv_cohort_analyses')
    op.drop_table('ltv_cohort_analyses')
    op.drop_index('ix_benchmark_tenant', table_name='industry_benchmarks')
    op.drop_index('ix_benchmark_industry', table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    op.drop_index('ix_emq_tenant_date', table_name='emq_measurements')
    op.drop_index('ix_emq_platform', table_name='emq_measurements')
    op.drop_table('emq_measurements')
    op.drop_index('ix_ltv_pred_tenant', table_name='customer_ltv_predictions')
    op.drop_index('ix_ltv_pred_segment', table_name='customer_ltv_predictions')
    op.drop_index('ix_ltv_pred_customer', table_name='customer_ltv_predictions')
    op.drop_table('customer_ltv_predictions')
    op.drop_index('ix_creative_tenant', table_name='creatives')
    op.drop_index('ix_creative_external', table_name='creatives')
    op.drop_table('creatives')
    op.drop_index('ix_latency_stats_tenant', table_name='conversion_latency_stats')
    op.drop_table('conversion_latency_stats')
    op.drop_index('ix_conv_latency_tenant', table_name='conversion_latencies')
    op.drop_index('ix_conv_latency_platform', table_name='conversion_latencies')
    op.drop_table('conversion_latencies')
    op.drop_index('ix_audience_tenant', table_name='audience_records')
    op.drop_index('ix_audience_external', table_name='audience_records')
    op.drop_table('audience_records')
    # Enum types are created implicitly by create_table above, but Alembic does
    # not emit the matching drops; without these a re-upgrade fails.
    for enum_name in (
        "conversionuploadstatus",
        "customersegment",
        "emqstatus",
        "experimentstatus",
        "reallocationstatus",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
